export const SET_DATADOG = 'SET_DATADOG';
export const SET_AZURE = 'SET_AZURE';
export const GET_DATADOG_ERROR = 'GET_DATADOG_ERROR';
export const GET_AZURE_ERROR = 'GET_AZURE_ERROR';
export const CLEAR_AZURE_ERROR = 'CLEAR_AZURE_ERROR';
export const CLEAR_DATADOG_ERROR = 'CLEAR_DATADOG_ERROR';